trigger:
  batch: true

variables:
  system.debug: "true"

stages:
  - stage: Build
    displayName: 🚧
    jobs:
      - job: BuildOnWindows
        displayName: "Build with VS 2019 on Windows"
        pool:
          vmImage: windows-2019
        steps:
          - bash: echo "##vso[task.setvariable variable=VERSION_SUFFIX]${BUILD_BUILDID}.${BUILD_SOURCEVERSION}"
            displayName: "Set Package VERSION_SUFFIX environment variable"
          - task: NuGetToolInstaller@1
          - task: NuGetCommand@2
            inputs:
              restoreSolution: Telegram.Bot.sln
          - task: VSBuild@1
            inputs:
              solution: Telegram.Bot.sln
              platform: Any CPU
              configuration: Release
          - publish: .
            artifact: windows-build

  - stage: UnitTest
    displayName: 🧪
    jobs:
      - job: UnitTest
        displayName: "Run Unit Tests with .NET Core 3.0 on "
        strategy:
          matrix:
            Windows:
              VM_IMAGE: windows-2019
            Ubuntu:
              VM_IMAGE: ubuntu-16.04
            macOS:
              VM_IMAGE: macOS-10.13
        pool:
          vmImage: $(VM_IMAGE)
        steps:
          - checkout: none
          - download: current
          - task: DotNetCoreInstaller@2
            displayName: "Install .NET Core 3.0"
            inputs:
              version: 3.0.100
          - task: DotNetCoreCLI@2
            displayName: "Initialize .NET Core Environment"
            inputs:
              command: custom
              custom: help
          - pwsh: dir -Recurse $(Pipeline.Workspace)
          - pwsh: dotnet test --configuration Release --no-build --framework netcoreapp3.0 --list-tests test/Telegram.Bot.Tests.Unit/
            displayName: "List Unit Tests"
            workingDirectory: $(Pipeline.Workspace)/windows-build
            failOnStderr: true
          - task: DotNetCoreCLI@2
            displayName: "List Unit Tests"
            inputs:
              command: test
              arguments: --configuration Release --no-build --framework netcoreapp3.0 --list-tests test/Telegram.Bot.Tests.Unit/
              workingDirectory: $(Pipeline.Workspace)/windows-build
